### ISSUE TITLE
cannot install in virtualenv

### ISSUE THREAD

**Issue by meejah** [rxcomm/pyaxo#18]
When I try to install this in a virtualenv, I get an error culminating in `error: could not create '/usr/share/pyaxo': Permission denied` which I guess stems from the `BASE_DIRECTORY` stuff in setup.py? (That said, only the thing on PyPI can't install; if I clone and `pip install --editable ` the master branch it seems to work.

**Comment by felipedau** [comment]
Thanks for reporting it @meejah!

Sorry about that, those files should have been removed a while ago. Once #19 is merged that should be fixed.

Just out of curiosity, what pip version do you have installed? On our tests using pip 9 the installation does not fail, but it ends up installing in the package's scope: `virtualenv/lib/python2.7/site-packages/usr/share/pyaxo/`! (And I believe that behavior started with pip 7)

**Comment by meejah** [comment]
Could have been a "forgot to upgrade pip" problem (on Debian, virtualenv ships with a really old pip).

In any case, whatever is on PyPI right now seems to work with both latest pip and the pip that ships with `python-virtualenv` on Debian jessie (which is 1.5.6 [!!]).

Thanks!

**Comment by felipedau** [comment]
On Fri, Feb 24, 2017 at 10:09:43AM -0800, meejah wrote:
> Could have been a "forgot to upgrade pip" problem (on Debian, virtualenv ships with a really old pip).

Well, at least we remembered to remove the files!

> In any case, whatever is on PyPI right now seems to work with both latest pip and the pip that ships with `python-virtualenv` on Debian jessie (which is 1.5.6 [!!]).

Awesome!

That's incredible, 1.5.6-5 is almost two years old :O

Thanks @meejah!
