### ISSUE TITLE
curve25519-donna is now on PyPI

### ISSUE THREAD

**Issue by warner** [rxcomm/pyaxo#4]
At @felipedau 's suggestion, I just published version 1.3 of "curve25519-donna" to PyPI. So I think you can remove the `dependency_links=` portion of your setup.py now.

**Comment by rxcomm** [comment]
Thanks for this!! @felipedau is fixing setup.py and docs to reflect that curve25519-donna is on pypi. That change should be committed later today.

**Comment by rxcomm** [comment]
Done
